name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags --prune --unshallow

      - name: Get previous tag
        id: get_previous_tag
        run: |
          CURRENT_TAG=${GITHUB_REF_NAME#refs/tags/}
          PREVIOUS_TAG=$(git tag --sort=-v:refname | grep -A1 "$CURRENT_TAG" | tail -n1)
          echo "current_tag=$CURRENT_TAG" >> $GITHUB_ENV
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_ENV
          echo "Previous tag: $PREVIOUS_TAG"
          echo "Current tag: $CURRENT_TAG"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.current_tag }}
          release_name: Release ${{ env.current_tag }}
          body: |
            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ env.previous_tag }}...${{ env.current_tag }}
          draft: false
          prerelease: false
